export const colors = [
  { name: "Pastellgelb", hex: "#FFF9C4" },
  { name: "Kanariengelb", hex: "#FFF176" },
  { name: "Sonnengelb", hex: "#FFEB3B" },
  { name: "Neon Gelb", hex: "#FFFF33" },
  { name: "Maisgelb", hex: "#FBC02D" },
  { name: "Bernstein", hex: "#F57F17" },
  { name: "Sandgelb", hex: "#c1bb92" },
  { name: "Beigegelb", hex: "#c5bb98" },
  { name: "Senfgelb", hex: "#c9c55e" },
  { name: "Goldgelb", hex: "#c7c34a" },
  { name: "Lindgelb", hex: "#cbc03b" },
  { name: "Zitronengelb", hex: "#acaa4a" },
  { name: "Ockerbeige", hex: "#c4a654" },
  { name: "Hellkhaki", hex: "#bebf9b" },
  { name: "Khakibeige", hex: "#c1c18b" },
  { name: "Cremebeige", hex: "#c5c1a2" },
  { name: "Beige Sand", hex: "#b7a38e" },
  { name: "Hellbeige", hex: "#bbae99" },
  { name: "Kieselbeige", hex: "#bfbda3" },
  { name: "Rosenholz", hex: "#b68b7b" },
  { name: "Hautbeige", hex: "#bca08a" },
  { name: "Lehmgrau", hex: "#c0b486" },
  { name: "Lachsbeige", hex: "#bb9b8b" },
  { name: "Warmbeige", hex: "#c1ab9a" },
  { name: "Terracottabraun", hex: "#b5695c" },
  { name: "Ziegelbraun", hex: "#b64d4a" },
  { name: "Kupferbraun", hex: "#ae4d4b" },
  { name: "Rötlichbraun", hex: "#a35d5a" },
  { name: "Mittelbraun", hex: "#814f4d" },
  { name: "Zimtbraun", hex: "#b66460" },
  { name: "Mahagoni", hex: "#b98986" },
  { name: "Mokka", hex: "#795548" },
  { name: "Schokobraun", hex: "#5D4037" },
  { name: "Kaffebraun", hex: "#3E2723" },
  { name: "Kupfer", hex: "#EF6C00" },
  { name: "Kürbis", hex: "#FB8C00" },
  { name: "Leuchtorange", hex: "#FF9800" },
  { name: "Mandarine", hex: "#FFB74D" },
  { name: "Apricot", hex: "#FFE0B2" },
  { name: "Neon Orange", hex: "#FF5F1F" },
  { name: "Bernstein Dunkel", hex: "#F57F17" },
  { name: "Senf", hex: "#AFB42B" },
  { name: "Sand", hex: "#A1887F" },
  { name: "Beigebraun", hex: "#bca08a" },
  { name: "Goldocker", hex: "#c4a654" },
  { name: "Honigbraun", hex: "#c8b28c" },
  { name: "Holzbraun", hex: "#91785b" },
  { name: "Erdbraun", hex: "#845f41" },
  { name: "Pastellrot", hex: "#FFCDD2" },
  { name: "Korallenrot", hex: "#E57373" },
  { name: "Signalrot", hex: "#F44336" },
  { name: "Reinrot", hex: "#ff0000" },
  { name: "Ferrari Rot", hex: "#FF2800" },
  { name: "Rubinrot", hex: "#D32F2F" },
  { name: "Weinrot", hex: "#B71C1C" },
  { name: "Rosenholz Dunkel", hex: "#b5695c" },
  { name: "Kupferrot Hell", hex: "#be6e62" },
  { name: "Korallenbraun", hex: "#bc7b75" },
  { name: "Pfirsichbraun", hex: "#c29088" },
  { name: "Altrosa", hex: "#F06292" },
  { name: "Rosé", hex: "#F8BBD0" },
  { name: "Altrosa (Koralle)", hex: "#FFE0DC" },
  { name: "Lachs", hex: "#FFAB9E" },
  { name: "Koralle", hex: "#FF6F61" },
  { name: "Terracotta", hex: "#E6513C" },
  { name: "Ziegelrot", hex: "#B53A2B" },
  { name: "Ockerrot", hex: "#c1874e" },
  { name: "Lehmbraun", hex: "#ac925f" },
  { name: "Ziegelrot Hell", hex: "#b64d4a" },
  { name: "Ziegelrot Mittel", hex: "#ae4d4b" },
  { name: "Ziegelrot Dunkel", hex: "#a35d5a" },
  { name: "Fuchsia Blaze", hex: "#FF33CC" },
  { name: "Himbeere", hex: "#E91E63" },
  { name: "Kirschrot", hex: "#C2185B" },
  { name: "Brombeere", hex: "#880E4F" },
  { name: "Lavendel", hex: "#E1BEE7" },
  { name: "Amethyst", hex: "#BA68C8" },
  { name: "Flieder", hex: "#9C27B0" },
  { name: "Pflaume", hex: "#7B1FA2" },
  { name: "Aubergine", hex: "#4A148C" },
  { name: "Malve", hex: "#D1C4E9" },
  { name: "Taubenlila", hex: "#9575CD" },
  { name: "Violett", hex: "#673AB7" },
  { name: "Königslila", hex: "#512DA8" },
  { name: "Nachtviolett", hex: "#311B92" },
  { name: "Veilchenblau", hex: "#7778dc" },
  { name: "Fliederblau", hex: "#8486d1" },
  { name: "Lavendelblau", hex: "#6f91d7" },
  { name: "Babyblau", hex: "#BBDEFB" },
  { name: "Himmelblau", hex: "#64B5F6" },
  { name: "Klarblau", hex: "#2196F3" },
  { name: "Jeansblau", hex: "#7986CB" },
  { name: "Königsblau", hex: "#3F51B5" },
  { name: "Marine", hex: "#1976D2" },
  { name: "Saphir", hex: "#303F9F" },
  { name: "Mitternachtsblau", hex: "#1A237E" },
  { name: "Nachtblau", hex: "#0D47A1" },
  { name: "Eisblau", hex: "#C5CAE9" },
  { name: "Taubenblau", hex: "#9bb5bc" },
  { name: "Eisblaugrau", hex: "#9bb1bf" },
  { name: "Silberblau", hex: "#a0b4bf" },
  { name: "Graublau", hex: "#99afb3" },
  { name: "Blaugrau Mittel", hex: "#a3acbd" },
  { name: "Stahlblau", hex: "#5873b5" },
  { name: "Perlblau", hex: "#7699d3" },
  { name: "Kobaltblau", hex: "#3d77d0" },
  { name: "Saphirblau", hex: "#265dd4" },
  { name: "Violettblau", hex: "#3932d5" },
  { name: "Türkis", hex: "#00BCD4" },
  { name: "Aquamarin", hex: "#4DD0E1" },
  { name: "Petrol", hex: "#0097A7" },
  { name: "Dunkelpetrol", hex: "#006064" },
  { name: "Türkisgrau", hex: "#9fb5b9" },
  { name: "Aquagrau", hex: "#aabcb7" },
  { name: "Meergrün", hex: "#9eb5b6" },
  { name: "Aqua-Blau", hex: "#63a393" },
  { name: "Meeresblau", hex: "#51ab8c" },
  { name: "Delftblau", hex: "#5c99c0" },
  { name: "Graublau Dunkel", hex: "#477d90" },
  { name: "Nachtblaugrau", hex: "#4b4b7e" },
  { name: "Mint", hex: "#C8E6C9" },
  { name: "Limonengrün", hex: "#DCEDC8" },
  { name: "Pastellgrün", hex: "#DCE775" },
  { name: "Apfelgrün", hex: "#AED581" },
  { name: "Limette", hex: "#8BC34A" },
  { name: "Frühlingsgrün", hex: "#81C784" },
  { name: "Smaragdgrün", hex: "#4CAF50" },
  { name: "Tannengrün", hex: "#388E3C" },
  { name: "Flaschengrün", hex: "#1B5E20" },
  { name: "Neon Grün", hex: "#39FF14" },
  { name: "Moosgrün", hex: "#689F38" },
  { name: "Olive", hex: "#33691E" },
  { name: "Olivgrün", hex: "#827717" },
  { name: "Lindgrün", hex: "#CDDC39" },
  { name: "Helloliv", hex: "#b2c46d" },
  { name: "Grünoliv", hex: "#8cbc51" },
  { name: "Mattoliv", hex: "#b4bf95" },
  { name: "Blassoliv", hex: "#beb99e" },
  { name: "Stauboliv", hex: "#bac4a7" },
  { name: "Olivgrau", hex: "#afbfa1" },
  { name: "Senfgrün", hex: "#aeb363" },
  { name: "Moosgrün Hell", hex: "#9ebf7e" },
  { name: "Waldoliv", hex: "#7e8f4b" },
  { name: "Tannengrün Hell", hex: "#74aa5d" },
  { name: "Blattgrün", hex: "#4eaa38" },
  { name: "Kräutergrün", hex: "#588852" },
  { name: "Apfeloliv", hex: "#a0af4d" },
  { name: "Khakigrün", hex: "#ac925f" },
  { name: "Hellkhaki", hex: "#bebf9b" },
  { name: "Khaki", hex: "#b9997c" },
  { name: "Senfgrün Dunkel", hex: "#929862" },
  { name: "Grauoliv", hex: "#898746" },
  { name: "Wolkenweiß", hex: "#FFFFFF" },
  { name: "Porzellan", hex: "#F5F5F5" },
  { name: "Silberweiß", hex: "#E0E0E0" },
  { name: "Lichtgrau", hex: "#CCCCCC" },
  { name: "Hellgrau", hex: "#CCCCCC" },
  { name: "Steingrau", hex: "#B3B3B3" },
  { name: "Aschgrau", hex: "#9eb5b6" },
  { name: "Betongrau", hex: "#a0b4bf" },
  { name: "Schiefergrau", hex: "#9bb1bf" },
  { name: "Dunkelgrau", hex: "#333333" },
  { name: "Anthrazit", hex: "#1A1A1A" },
  { name: "Tiefschwarz", hex: "#000000" },
];

export const lastUsedColors = [
  { name: "Front", hex: "#FF5733" },
  { name: "Back", hex: "#33FF57" },
  { name: "Left Sleeve", hex: "#3357FF" },
  { name: "Right Sleeve", hex: "#FFFFFF" },
  { name: "Collar", hex: "#000000" },
  { name: "Sticker One", hex: "#888888" },
  { name: "Sticker Two", hex: "#888888" },
  { name: "number One", hex: "#FFFF00" },
  { name: "Number Two", hex: "#CCCCCC" },
  { name: "Name One", hex: "#CCCCCC" },
  { name: "Name Two", hex: "#CCCCCC" },
  { name: "Design", hex: "#CCCCCC" },
];
